spring:
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
#    database: h2
  h2:
    console:
      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/knuapp?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: knuapp

server:
  port: 8888

